#!/bin/sh

alias mandeye_start="sudo systemctl start mandeye_controller.service"
alias mandeye_stop="sudo systemctl stop mandeye_controller.service"
alias mandeye_status="sudo systemctl status mandeye_controller.service"
alias mandeye_log="journalctl -u mandeye.service"
alias mandeye_fakepps_start="sudo systemctl start mandeye_fakepps.service"
alias mandeye_fakepps_stop="sudo systemctl stop mandeye_fakepps.service"
alias mandeye_fakepps_status="sudo systemctl status mandeye_fakepps.service"
alias mandeye_fakepps_log="journalctl -u mandeye_fakepps.service"
alias GPIO_BUZZER_ON="raspi-gpio set 24 op && raspi-gpio set 24 dh"
alias GPIO_BUZZER_OFF="raspi-gpio set 24 dl"
alias mandeye_test="curl 127.0.0.1:8003/json/status --silent"
alias mandeye_gnss_sattelites="mandeye_test | grep satellites_tracked"

alias mandeye_cam0_status="sudo systemctl status mandeye_libcamera_cam0.service"
alias mandeye_cam1_status="sudo systemctl status mandeye_libcamera_cam1.service"
alias mandeye_cam0_stop="sudo systemctl stop mandeye_libcamera_cam0.service"
alias mandeye_cam1_stop="sudo systemctl stop mandeye_libcamera_cam1.service"
alias mandeye_cam0_start="sudo systemctl start mandeye_libcamera_cam0.service"
alias mandeye_cam1_start="sudo systemctl start mandeye_libcamera_cam1.service"
alias mandeye_cam0_log="journalctl -u mandeye_libcamera_cam0.service"
alias mandeye_cam1_log="journalctl -u mandeye_libcamera_cam1.service"

alias mandeye_phc2sys_status="sudo systemctl status mandeye_phc2sys-gm-eth0.service"
alias mandeye_phc2sys_start="sudo systemctl start mandeye_phc2sys-gm-eth0.service"
alias mandeye_phc2sys_stop="sudo systemctl stop mandeye_phc2sys-gm-eth0.service"
alias mandeye_phc2sys_log="journalctl -u mandeye_phc2sys-gm-eth0.service"
alias mandeye_ptp4l_status="sudo systemctl status mandeye_ptp4l-gm-eth0.service"
alias mandeye_ptp4l_grandmaster_start="sudo systemctl start mandeye_ptp4l-gm-eth0.service"
alias mandeye_ptp4l_grandmaster_stop="sudo systemctl stop mandeye_ptp4l-gm-eth0.service"
alias mandeye_ptp4l_grandmaster_log="journalctl -u mandeye_ptp4l-gm-eth0.service"

alias mandeye_services_status="bash /opt/mandeye/check_services.sh"
