#!/usr/bin/env python3
"""
Generate gold CDR bytes for PointCloud2 and Imu messages using ROS2 rclpy.

Usage:
    source /opt/ros/humble/setup.bash
    python3 gen_cdr_gold.py > cdr_gold_data.h
"""
import struct
import rclpy.serialization
from builtin_interfaces.msg import Time
from geometry_msgs.msg import Quaternion, Vector3
from sensor_msgs.msg import Imu, PointCloud2, PointField
from std_msgs.msg import Header

# ===========================================================================
# PointCloud2 gold
# ===========================================================================

PC2_STAMP_SEC  = 100
PC2_STAMP_NSEC = 1_000_000
PC2_FRAME_ID   = "lidar"
PC2_POINT_STEP = 28

# (x, y, z, intensity, ring, timestamp_ns)
PC2_PTS = [
    (1.0, 2.0, 3.0, 100.0, 0, 100_000_000_000),
    (4.0, 5.0, 6.0, 200.0, 1, 100_001_000_000),
]
t0 = PC2_PTS[0][5] * 1e-9  # 100.0 s

raw_data = bytearray()
for x, y, z, intensity, ring, ts in PC2_PTS:
    rel_time = ts * 1e-9 - t0
    raw_data += struct.pack('<ffff', x, y, z, intensity)
    raw_data += struct.pack('<HH', ring, 0)
    raw_data += struct.pack('<d', rel_time)

pc2_msg = PointCloud2(
    header=Header(stamp=Time(sec=PC2_STAMP_SEC, nanosec=PC2_STAMP_NSEC),
                  frame_id=PC2_FRAME_ID),
    height=1,
    width=len(PC2_PTS),
    fields=[
        PointField(name='x',         offset=0,  datatype=PointField.FLOAT32, count=1),
        PointField(name='y',         offset=4,  datatype=PointField.FLOAT32, count=1),
        PointField(name='z',         offset=8,  datatype=PointField.FLOAT32, count=1),
        PointField(name='intensity', offset=12, datatype=PointField.FLOAT32, count=1),
        PointField(name='ring',      offset=16, datatype=PointField.UINT16,  count=1),
        PointField(name='time',      offset=20, datatype=PointField.FLOAT64, count=1),
    ],
    is_bigendian=False,
    point_step=PC2_POINT_STEP,
    row_step=PC2_POINT_STEP * len(PC2_PTS),
    data=bytes(raw_data),
    is_dense=True,
)
pc2_cdr = rclpy.serialization.serialize_message(pc2_msg)

# ===========================================================================
# Imu gold
# ===========================================================================

IMU_STAMP_SEC  = 200
IMU_STAMP_NSEC = 250_000_000
IMU_FRAME_ID   = "lidar"
IMU_GYRO       = (0.1, 0.2, 0.3)   # rad/s
IMU_ACCEL      = (1.0, 2.0, 9.81)  # m/s²

imu_msg = Imu(
    header=Header(stamp=Time(sec=IMU_STAMP_SEC, nanosec=IMU_STAMP_NSEC),
                  frame_id=IMU_FRAME_ID),
    orientation=Quaternion(x=0.0, y=0.0, z=0.0, w=1.0),
    orientation_covariance=[-1.0] + [0.0] * 8,
    angular_velocity=Vector3(x=IMU_GYRO[0], y=IMU_GYRO[1], z=IMU_GYRO[2]),
    angular_velocity_covariance=[0.0] * 9,
    linear_acceleration=Vector3(x=IMU_ACCEL[0], y=IMU_ACCEL[1], z=IMU_ACCEL[2]),
    linear_acceleration_covariance=[0.0] * 9,
)
imu_cdr = rclpy.serialization.serialize_message(imu_msg)

# ===========================================================================
# Emit header
# ===========================================================================

def emit_array(name, data):
    print(f"static const uint8_t  {name}[{len(data)}] = {{")
    for i, b in enumerate(data):
        if i % 16 == 0:
            print("    ", end="")
        print(f"0x{b:02x},", end=" ")
        if i % 16 == 15 or i == len(data) - 1:
            print()
    print("};")
    print(f"static const size_t {name}Size = {len(data)};")
    print()

print("// DO NOT EDIT — generated by gen_cdr_gold.py")
print("#pragma once")
print("#include <cstddef>")
print("#include <cstdint>")
print()
print("// PointCloud2: stamp={sec=100,nsec=1000000}, frame_id='lidar',")
print("// 2 pts: (1,2,3,100,ring=0,ts=100e9ns) and (4,5,6,200,ring=1,ts=100.001e9ns)")
emit_array("kGoldPc2", pc2_cdr)
print("// Imu: stamp={sec=200,nsec=250000000}, frame_id='lidar',")
print(f"// gyro=({IMU_GYRO[0]},{IMU_GYRO[1]},{IMU_GYRO[2]}) rad/s,")
print(f"// accel=({IMU_ACCEL[0]},{IMU_ACCEL[1]},{IMU_ACCEL[2]}) m/s²")
emit_array("kGoldImu", imu_cdr)
